### PR TITLE
Added "push" method to insert IP at top of the chain

### PR DESCRIPTION
**Pull request by jfirles**
Method to insert IP at top of the chain.

### CODE REVIEW

**Review by fredposner — CHANGES_REQUESTED** [review]
There's already an addip, blockip, and method POST. What would be the reason for puship?

**Comment by jfirles** [comment]
The use of push would be to be able to jump to other firewall chains. With the "addip" the software append the rule at the end and I need the last rule to be the "jump rule" to another chain.

Example:
1. Create two "ipsets", one called "whitelist" and the other called "allowin". In the first one will be the IP's that should never be banned, in the second one, the IP's of the countries from which we accept traffic.
2. Create the chain "APIBANLOCAL" and add a rule that jumps to the chain "ALLOWEDINCHAIN".
3. In the "INPUT" chain:
  - If the origin is in the "whitelist" ipset, it is accepted.
  - If the origin is not in the ipset "whitelist", we jump to the chain "APIBANLOCAL".
4. With kamailio I insert and delete the IP's with the http client (here is where I need the rule inserted in point 2 to remain the last one, that's why I need the "push").
5. In the "ALLOWEDINCHAIN" chain:
  - If the origin is in the "allowin" ipset, it is accepted.
  - If the source is not in the "allowin" ipset, the traffic is denied.

Example script:
ipset create whitelist nethash
ipset create allowin nethash
...load cidrs in "whitelist" and "allowin" from geoip database...
iptables -A INPUT -m set --match-set whitelist src -j ACCEPT
iptables -N APIBANLOCAL
iptables -N ALLOWEDINCHAIN
iptables -A INPUT -j APIBANLOCAL
iptables -A APIBANLOCAL -j ALLOWEDINCHAIN
iptables -A ALLOWEDINCHAIN -m set --match-set allowin src -j ACCEPT
iptables -A ALLOWEDINCHAIN -j DROP
...start iptables-api...

**Review by fredposner — CHANGES_REQUESTED** [review]
This makes a lot more sense... I do have the following requests:

* in the router.HandleFunc section (line 74), lets move this to between flushchain and removeip to keep with the alphabetical nature. I know it's kind of an OCD request, but makes sense to me.
* same for the case of "push" (line 200). If we can move this to after flush
* bigger concern:
  * the appendunique function won't allow an IP to be added twice. My understanding (and testing over a year ago) showed that Insert did allow duplicate entries.
  * Have you tested adding the same IP more than once?
  * Assuming that is allowed, we would need some aspect of parsing the existing records to prevent duplication (may just be an Exists call)

Thank you for the submission and the detailed explanation / example.

**Comment by jfirles** [comment]
I solved the two first points and I added a check to avoid duplicated entries with the Exists method.

I'm not a go programmer so, please, if something is wrong, change it.

**Comment by fredposner** [comment]
Thank you @jfirles for contributing.

**Pull request merged**
